### ISSUE TITLE
Abhaken d. Veranstaltung

### ISSUE THREAD

**Issue by kotarokun** [HeikoRadde/Lernzielnator#2]
Hallo,

wenn ich die Veranstaltung als Ausgearbeitet abharke, und auf die nächste Ausarbeitung klicke, ist das Häkchen noch bei Ausarbeitung drin, er aktualisiert dies nicht.

zudem wäre es klasse, wenn man eine übergeordnete Instanz wie die Veranstaltung mit ein klick auf Ausgearbeitet auch die einzelnen LZ abgearbeitet wären. Bei Wochenweise und größeren Instanzen würde ich eine Nachfrage wünschen. 

ich wollte Fragen, ob du auch den MSM 2.0 drinn hast? Wir haben ja ein anderen Link für die LLP..

**Comment by HeikoRadde** [comment]
Hallo,
der Link zu den LLP des MSM2.0 ist doch folgender, oder?
https://lernziele.charite.de/zend/studentenlernziele/index/studiengang/Modellstudiengang2
Wie ich sehe werden hiervon exportierte Lernziele nicht korrekt importiert. Die Lösung dieses Problems ist in Arbeit.

**Comment by HeikoRadde** [comment]
Behoben in Verison 1.1
